./article-ids.sh
./category-ids.sh
./article-categories.sh
./edges.sh
./graph-components.sh
./finished-paths.sh
./percentage-paths.sh
./category-paths.sh
./category-subtree-paths.sh
./category-pairs.sh
./category-ratios.sh
