
import pandas as pd

# importing categories.tsv file into dataframe df
tsv_file = open("wikispeedia_paths-and-graph/categories.tsv")
df = pd.read_csv(tsv_file, delimiter="\t", names = ["article_name", "category_name","article_id","categoryid1","categoryid2","categoryid3"])
# Dropping initial introductory rows
df = df.loc[12:]
df.reset_index(inplace =True)
df.drop("index", axis =1, inplace = True)

# Matching article names in categories.tsv and article-id.csv to assign article id to df

# importing article-id.csv (generated by q1) in articleid_df
articleid_df = pd.read_csv("article-id.csv");
# setting article name as index
articleid_df.set_index("article_name", inplace = True)
# getting article id from article name of df in a series- new
new = articleid_df.loc[df["article_name"], "article_id"]
# created a dataframe k from series- new
k = pd.DataFrame(new)
k.reset_index(inplace = True)
# copied article ids from k to df
df["article_id"] = k["article_id"]

df.drop("article_name", axis = 1, inplace = True)

# importing category-id.csv (generated by q2) in category_df
category_df = pd.read_csv("category-id.csv");
# setting category name as index
category_df.set_index("category_name", inplace = True)

'''
debugging
# print(df)
# print(category_df)
# print(df.loc[0,"category_name"])

'''

# Matching category names to assign category id to df
idlist = []
i = 0
while( i < df.shape[0]-1):
    if(df.loc[i,"article_id"] == df.loc[i+2,"article_id"]):
        lst1 = df.loc[i,"category_name"]
        lst2 = df.loc[i+1,"category_name"]
        lst3 = df.loc[i+2,"category_name"]
        lst4 = lst1+ lst2 + lst3
        lst = [df.loc[i,"category_name"],df.loc[i+1,"category_name"],df.loc[i+2,"category_name"]]
        # [lst.append(x) for x in lst4 if x not in lst]
        k =3 - len(lst)
        for j in range(len(lst)):
            idlist.append(category_df.loc[lst[j], "category_id"])
        for m in range(0,k):
            idlist.append("")
        df.loc[i,"categoryid1":"categoryid3"] = idlist
        idlist.clear()
        i+=2;

    elif(df.loc[i,"article_id"] == df.loc[i+1,"article_id"]):
        lst1 = df.loc[i,"category_name"]
        lst2 = df.loc[i+1,"category_name"]
        lst4 = lst1+ lst2
        lst =[]
        lst = [df.loc[i,"category_name"],df.loc[i+1,"category_name"]]
        # [lst.append(x) for x in lst4 if x not in lst]
        k =3 - len(lst)
        for j in range(len(lst)):
            idlist.append(category_df.loc[lst[j], "category_id"])
        for m in range(0,k):
            idlist.append("")
        df.loc[i,"categoryid1":"categoryid3"] = idlist
        idlist.clear()
        i=i+1;

    else:
        lst = df.loc[i,"category_name"]
        k =3
        k = k -1
        # for j in range(len(lst)):
        idlist.append(category_df.loc[lst, "category_id"])
        for m in range(0,k):
            idlist.append("")
        df.loc[i,"categoryid1":"categoryid3"] = idlist
        idlist.clear()
    i+=1

# appending last row
lst = df.loc[i,"category_name"]
k =3
k = k - 1
# for j in range(len(lst)):
idlist.append(category_df.loc[lst, "category_id"])
for m in range(0,k):
    idlist.append("")
df.loc[i,"categoryid1":"categoryid3"] = idlist
idlist.clear()

df.drop("category_name", axis =1, inplace = True)
df.dropna(inplace = True)

# Adding the article ids that are not present in category.tsv file and assigning them the id of subject i.e. C0001
nlst = []
i =1
for index, row in df.iterrows():
    if(row["article_id"]!="A" + "%04d"%i):
        nlst.append("A" + "%04d"%i)
        i+=1
    i+=1

df2 = pd.DataFrame()
df2["article_id"] = nlst
df2["categoryid1"] = "C0001"
# Concating the dataframes
df = pd.concat([df,df2])
df.sort_values(by="article_id", inplace = True)

# Exporting df to article-categories.csv
df.to_csv("article-categories.csv", index = False)
print("\nOutput file generated - article-categories.csv\n")

# print(df)
